version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    networks: #ここを追加
      - app-network #ここを追加
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DATABASE_URL: postgres://postgres:postgres@db:5432/quiz_development
      RAILS_ENV: quiz_development #追加
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - db
    networks: #ここを追加
      - app-network #ここを追加

volumes:
  postgres_volume:
networks: #ここを追加
  app-network: #ここを追加

# https://zenn.dev/hs7/articles/2cc4d67650ba69